service: option-crawl

frameworkVersion: '>=1.1.0 <2.0.0'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  crawlRequest:
    handler: api/crawl.request
    memorySize: 128
    description: Get URL and return crawled data.
    events:
      - http:
          path: crawl
          method: get
